services:
  pgdatabase:
    image: postgres:18-alpine
    container_name: postgres_18_retail
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=retail_db
    volumes:
      - ./ny_postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - pg-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_retail
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "8080:80"
    networks:
      - pg-network

    networks:
      pg-network:
        driver: bridge
      redpanda:
        image: ://docker.redpanda.com
        container_name: redpanda_streaming
        ports:
          - "9092:9092"
      spark:
        image: bitnami/spark:3.5
        container_name: spark_worker
        environment:
          - SPARK_MODE=master
        ports:
          - "8081:8081"
