version: '3.8'
services:
  redpanda: # Kafka-compatible (Streaming)
    image: ://redpanda.com
    ports: ["9092:9092"]
  
  postgres_olap: # Data Warehouse (OLAP)
    image: postgres:15
    environment:
      POSTGRES_DB: analytics
      POSTGRES_PASSWORD: admin_password
    ports: ["5432:5432"]

  metabase: # BI / Dashboarding
    image: metabase/metabase:latest
    ports: ["3000:3000"]
    depends_on:
      - postgres_olap

  prometheus: # Monitoreo de Pipelines
    image: prom/prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports: ["9090:9090"]
