graph TD
    subgraph CI_CD_Quality
        GA[GitHub Actions] -->|Linter| SF[SQLFluff]
        GA -->|Tests| DT[dbt test]
    end

    subgraph Runtime_Observability
        AF[Airflow] -->|Metrics| PR[Prometheus]
        PR -->|Visual| GR[Grafana Dashboard]
        AF -->|On Failure| SL[Slack Webhook]
    end

    subgraph Data_Lifecycle
        S3[S3 Landing] -->|90 days| GL[AWS Glacier - Archivo]
        S3 -->|Expiration| RM[Delete Old Logs]
    end

>     DT -.->|Success| AF
>     style SL fill:#ff9999,stroke:#333
>     style GR fill:#99ff99,stroke:#333
